version: "3.7"

services:
  deltalake:
    image: newfrontdocker/delta-docker:3.2.0
    hostname: dl-hitchhikers_guide
    container_name: dl-hitchhikers_guide
    environment:
      - SPARK_LOCAL_HOSTNAME=localhost
      - PYSPARK_TOTAL_CORES=${PYSPARK_TOTAL_CORES:-4}
      - PYSPARK_DRIVER_MEMORY=${PYSPARK_DRIVER_MEMORY:-8g}
    volumes:
      - ${PWD}:/opt/spark/work-dir/hitchhikers_guide
      - ./startup.sh:/opt/spark/work-dir/startup.sh
    networks:
      - dais
    ports:
      - 8888-8889:8888-8889
      - 4040:4040
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 4G
    restart: unless-stopped

networks:
  dais:
    external: true
    name: dais